### ISSUE TITLE
Year-Long Reading Challenge

### ISSUE THREAD

**Issue by irmerk** [bookworm-reads/server#40] opened 2024-01-26 00:31 UTC
## Context

> keep thinking on this. maybe reading challenge is “annual tracker” or smthng 
> 
> maybe “intentions” instead of  goal/challenge? 
> 
> check out noom https://www.noom.com/programs/mood/
> 
> problems arise because a lot of current code is dependent on the assumption that there’s only one goal active at a time

**Comment by ameliagoodman** [comment] 2024-01-30 00:31
closing because this is duplicate of #1

**Closed by ameliagoodman** 2024-01-30 00:31 UTC
Labels: Complexity: Medium, Effort: 5, Priority: High ⚠️, State: Pending, Type: Feature Request 🛍️, Stack: Full
